# Generated by Django 3.2.24 on 2024-04-12 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producttype',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.producttype'),
            preserve_default=False,
        ),
    ]
