# Generated by Django 3.2.24 on 2024-04-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_customer_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='position',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
