# Generated by Django 3.2.24 on 2024-04-15 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_customer_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.product'),
            preserve_default=False,
        ),
    ]
