# Generated by Django 3.2.24 on 2024-04-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_record_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='main.customer'),
            preserve_default=False,
        ),
    ]
