# Generated by Django 3.2.24 on 2024-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_record_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['identity_number']},
        ),
        migrations.AlterField(
            model_name='record',
            name='set_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='unset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
