# Generated by Django 3.2.24 on 2024-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20240416_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['surname', 'name']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['set_date']},
        ),
        migrations.AddField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
