# Generated by Django 3.2.24 on 2024-04-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20240419_1412'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('surname', 'name', 'middlename')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('identity_number', 'name')},
        ),
    ]
