# Generated by Django 3.2.24 on 2025-01-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20240419_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='start_job',
            field=models.DateField(blank=True, null=True, verbose_name='Поступление'),
        ),
        migrations.AddField(
            model_name='product',
            name='stop_job',
            field=models.DateField(blank=True, null=True, verbose_name='Списание'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='auditory',
            field=models.CharField(max_length=4, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='identity_number',
            field=models.CharField(max_length=10, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='record',
            name='set_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='record',
            name='unset_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
